### ISSUE TITLE
Fingerprints don't work after restore

### ISSUE THREAD

**Issue by bege10** [ziandzivan/data_restore#2]
Hello,
after restore most things work fine.
As previously reported for a browser now some more apps crash and data must be cleared but can be restored with a backup/restore app.
More serious is that fingerprints to unlock the phone and apps don't work after restore. The fingerprint sensor reacts once with vibration but does not unlock. Then no more reaction.

- Tried to remove the 2 stored fingerprints. One succeeded, the second one remained. Adding new ones not possible (+ button greyed out).
- Rebooted the phone
- Could remove the second fingerprint and add new ones.
- The phone and one app accept fingerprints again.
- Another app still reacts as before. One vibration, then nothing. Didn't find a way to get it accept fingerprints again, need to use pattern to unlock

Fairphone 3, /e/OS (based on LineageOS for microG, Android 12)

**Comment by ziandzivan** [comment]
Hi
Unfortunately I cannot solve this without the phone.
Mainly the script was developed for my phone I have, Google Pixel, and for few ones in my family that are available for me. It is for stock OS and its next OTAs.
The best way would be another script for each model of a phone, its OS... they are different.

**Comment by bege10** [comment]
> Hi Unfortunately I cannot solve this without the phone. Mainly the script was developed for my phone I have, Google Pixel, and for few ones in my family that are available for me. It is for stock OS and its next OTAs. The best way would be another script for each model of a phone, its OS... they are different.

I see. Thank you anyway. I used to have TWRP data backups. But since Android 12 they don't work on older devices any more. Unfortunately from one Android version to the other things are getting more complicated if you don't just follow what Google wants you to do.
